include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

test:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/golang:1.21.1
  script:
    - make test

build-docker-image:
  extends: .build-docker-image

run-campaign:
  variables:
    GIT_STRATEGY: clone # clone entire repo instead of reusing workspace
    GIT_DEPTH: 0
    CHART_NAME: k8s-platform-aws-ebs-csi-driver
    COMPONENT: driver
  extends: .run-campaign
