include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

test:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/golang:1.22.2
  variables:
    GOTOOLCHAIN: "auto"
    KUBERNETES_CPU_REQUEST: "4"
    KUBERNETES_MEMORY_REQUEST: "8Gi"
    KUBERNETES_MEMORY_LIMIT: "8Gi"
  script:
    - make test

verify-fips:
  stage: build
  tags: [ "runner:main" ]
  image: $CURRENT_CI_IMAGE
  script:
    - *export-github-token
    - git config --global url."https://${GITHUB_TOKEN}@github.com/DataDog".insteadOf https://github.com/DataDog
    - make verify-fips

build-docker-image:
  extends: .build-docker-image
